project_id = "kyfejzsvteoxdvcdncvb"

[functions.spotify-auth]
verify_jwt = false

[functions.spotify-player]
verify_jwt = false

[functions.youtube-search]
verify_jwt = false

[functions.soundcloud-auth]
verify_jwt = false

[functions.soundcloud-player]
verify_jwt = false

[functions.soundcloud-proxy]
verify_jwt = false

[functions.spotify-artist]
verify_jwt = true
